### ISSUE TITLE
Call to a member function format() on null 

### ISSUE THREAD

**Issue by RimuruChan** [Innei/PaulTheme-for-typecho#9]
安装后进入主页显示（已开启debug）

Call to a member function format() on null
Error: Call to a member function format() on null in /www/wwwroot/sprite233.top/var/Widget/Abstract/Contents.php:773
Stack trace:
#0 /www/wwwroot/sprite233.top/usr/themes/paul/footer.php(65): Widget_Abstract_Contents->date('Y')
#1 /www/wwwroot/sprite233.top/var/Widget/Archive.php(1937): require('/www/wwwroot/sp...')
#2 /www/wwwroot/sprite233.top/usr/themes/paul/index.php(189): Widget_Archive->need('footer.php')
#3 /www/wwwroot/sprite233.top/var/Widget/Archive.php(2022): require_once('/www/wwwroot/sp...')
#4 /www/wwwroot/sprite233.top/var/Typecho/Router.php(138): Widget_Archive->render()
#5 /www/wwwroot/sprite233.top/index.php(23): Typecho_Router::dispatch()
#6 {main}

**Comment by RimuruChan** [comment]
发现原因并修复。

原因：没有任何文章

修复：发送任意文章

建议加个null判断
